/*-------------------------------------------------------------*/
/*  CLB - Cudne LB - Stencil Version                           */
/*     CUDA based Adjoint Lattice Boltzmann Solver             */
/*     Author: Lukasz Laniewski-Wollk                          */
/*     Developed at: Warsaw University of Technology - 2012    */
/*-------------------------------------------------------------*/


#ifndef CONFIG_H
  #include "../config.h"
  #define CONFIG_H 
#endif

#ifndef CONSTS_H
#define CONSTS_H 

#define VERSION "ded67cd"
#define MODEL "d3q27_pf_velocity_q27_geometric"
#define NUMBER_OF_DENSITIES 66

#ifdef CROSS_CPU
  #define MAX_THREADS 1
#else
  #define MAX_THREADS 128
#endif

#define PART_MAR 0.500000
#define PART_MAR_BOX 0.000000


#define NODE_Centerline      0x0001 
#define NODE_Spiketrack      0x0002 
#define NODE_Saddletrack     0x0003 
#define NODE_Bubbletrack     0x0004 
#define NODE_Smoothing       0x0005 
#define NODE_flux_nodes      0x0006 
#define NODE_NVelocity       0x0008 
#define NODE_NPressure       0x0010 
#define NODE_EVelocity       0x0018 
#define NODE_EPressure       0x0020 
#define NODE_SVelocity       0x0028 
#define NODE_SPressure       0x0030 
#define NODE_WVelocity       0x0038 
#define NODE_WPressure       0x0040 
#define NODE_FVelocity       0x0048 
#define NODE_FPressure       0x0050 
#define NODE_BVelocity       0x0058 
#define NODE_BPressure       0x0060 
#define NODE_MovingWall_N    0x0068 
#define NODE_MovingWall_S    0x0070 
#define NODE_Solid           0x0078 
#define NODE_Wall            0x0080 
#define NODE_BGK             0x0100 
#define NODE_MRT             0x0200 
#define ZONE_DefaultZone     0x0000 
#define NODE_None            0x0000 
#define NODE_Clear           0x0000 
#define NODE_ADDITIONALS     0x0007 
#define NODE_BOUNDARY        0x00f8 
#define NODE_COLLISION       0x0300 
#define NODE_SETTINGZONE     0xfc00 
#define NODE_NONE            0x0000 
#define NODE_ALL             0xffff 

#define SETTINGS                                    88 
#define  SETTINGS_Density_h                          0 
#define  SETTINGS_Density_l                          1 
#define  SETTINGS_PhaseField_h                       2 
#define  SETTINGS_PhaseField_l                       3 
#define  SETTINGS_IntWidth                           4 
#define  SETTINGS_omega_phi                          5 
#define  SETTINGS_M                                  6 
#define  SETTINGS_sigma                              7 
#define  SETTINGS_force_fixed_iterator               8 
#define  SETTINGS_Washburn_start                     9 
#define  SETTINGS_Washburn_end                      10 
#define  SETTINGS_minGradient                       11 
#define  SETTINGS_UseStage7SignedWallGhost          12 
#define  SETTINGS_Stage7SignedMode                  13 
#define  SETTINGS_Stage7DeltaQScale                 14 
#define  SETTINGS_Stage7DeltaQAbsCap                15 
#define  SETTINGS_Stage7DenomFloor                  16 
#define  SETTINGS_Stage7ActiveCMin                  17 
#define  SETTINGS_Stage7ActiveGradMin               18 
#define  SETTINGS_Stage7ActiveTangentMin            19 
#define  SETTINGS_Stage7RelaxationTau               20 
#define  SETTINGS_Stage8GradientWettingMode         21 
#define  SETTINGS_Stage8ActiveCMin                  22 
#define  SETTINGS_Stage8ActiveGradMin               23 
#define  SETTINGS_Stage8ActiveTangentMin            24 
#define  SETTINGS_Stage8RelaxationTau               25 
#define  SETTINGS_Stage8UseLocalWallAngle           26 
#define  SETTINGS_Stage8UseWallGeomNormal           27 
#define  SETTINGS_Stage8NormalDotMin                28 
#define  SETTINGS_Stage8MaxGradDelta                29 
#define  SETTINGS_Stage8OperatorMode                30 
#define  SETTINGS_Stage8DiagSphereCenterX           31 
#define  SETTINGS_Stage8DiagSphereCenterY           32 
#define  SETTINGS_Stage8DiagSphereCenterZ           33 
#define  SETTINGS_Stage8DiagSphereRadius            34 
#define  SETTINGS_Stage8CandidateVersion            35 
#define  SETTINGS_Stage8MaxNormalDelta              36 
#define  SETTINGS_Stage8MaxNormalDeltaRatio         37 
#define  SETTINGS_Stage8UseSmoothActiveWeight       38 
#define  SETTINGS_Stage8ActiveCSoftWidth            39 
#define  SETTINGS_Stage8TangentSoftMin              40 
#define  SETTINGS_Stage8CurvatureRelaxation         41 
#define  SETTINGS_RTI_Characteristic_Length         42 
#define  SETTINGS_pseudo2D                          43 
#define  SETTINGS_Radius                            44 
#define  SETTINGS_CenterX                           45 
#define  SETTINGS_CenterY                           46 
#define  SETTINGS_CenterZ                           47 
#define  SETTINGS_BubbleType                        48 
#define  SETTINGS_CapInit                           49 
#define  SETTINGS_CapInitRadius                     50 
#define  SETTINGS_CapInitTheta                      51 
#define  SETTINGS_CapInitCenterX                    52 
#define  SETTINGS_CapInitCenterY                    53 
#define  SETTINGS_CapInitCenterZ                    54 
#define  SETTINGS_SphereCapInit                     55 
#define  SETTINGS_SphereCapInitParentRadius         56 
#define  SETTINGS_SphereCapInitCenterX              57 
#define  SETTINGS_SphereCapInitCenterY              58 
#define  SETTINGS_SphereCapInitCenterZ              59 
#define  SETTINGS_SphereCapInitSolidCenterX         60 
#define  SETTINGS_SphereCapInitSolidCenterY         61 
#define  SETTINGS_SphereCapInitSolidCenterZ         62 
#define  SETTINGS_SphereCapInitSolidRadius          63 
#define  SETTINGS_DonutTime                         64 
#define  SETTINGS_Donut_h                           65 
#define  SETTINGS_Donut_D                           66 
#define  SETTINGS_Donut_x0                          67 
#define  SETTINGS_HEIGHT                            68 
#define  SETTINGS_developedFlow                     69 
#define  SETTINGS_developedPipeFlow                 70 
#define  SETTINGS_developedPipeFlow_X               71 
#define  SETTINGS_pipeRadius                        72 
#define  SETTINGS_pipeCentre_Y                      73 
#define  SETTINGS_pipeCentre_Z                      74 
#define  SETTINGS_tau_l                             75 
#define  SETTINGS_tau_h                             76 
#define  SETTINGS_tauUpdate                         77 
#define  SETTINGS_Viscosity_l                       78 
#define  SETTINGS_Viscosity_h                       79 
#define  SETTINGS_GravitationX                      80 
#define  SETTINGS_GravitationY                      81 
#define  SETTINGS_GravitationZ                      82 
#define  SETTINGS_BuoyancyX                         83 
#define  SETTINGS_BuoyancyY                         84 
#define  SETTINGS_BuoyancyZ                         85 
#define  SETTINGS_xyzTrack                          86 
#define  SETTINGS_Threshold                         87 
#define DENSITYALL                                  66 
#define  DENSITYALL_g0                               0 
#define  DENSITYALL_g1                               1 
#define  DENSITYALL_g2                               2 
#define  DENSITYALL_g3                               3 
#define  DENSITYALL_g4                               4 
#define  DENSITYALL_g5                               5 
#define  DENSITYALL_g6                               6 
#define  DENSITYALL_g7                               7 
#define  DENSITYALL_g8                               8 
#define  DENSITYALL_g9                               9 
#define  DENSITYALL_g10                             10 
#define  DENSITYALL_g11                             11 
#define  DENSITYALL_g12                             12 
#define  DENSITYALL_g13                             13 
#define  DENSITYALL_g14                             14 
#define  DENSITYALL_g15                             15 
#define  DENSITYALL_g16                             16 
#define  DENSITYALL_g17                             17 
#define  DENSITYALL_g18                             18 
#define  DENSITYALL_g19                             19 
#define  DENSITYALL_g20                             20 
#define  DENSITYALL_g21                             21 
#define  DENSITYALL_g22                             22 
#define  DENSITYALL_g23                             23 
#define  DENSITYALL_g24                             24 
#define  DENSITYALL_g25                             25 
#define  DENSITYALL_g26                             26 
#define  DENSITYALL_h0                              27 
#define  DENSITYALL_h1                              28 
#define  DENSITYALL_h2                              29 
#define  DENSITYALL_h3                              30 
#define  DENSITYALL_h4                              31 
#define  DENSITYALL_h5                              32 
#define  DENSITYALL_h6                              33 
#define  DENSITYALL_h7                              34 
#define  DENSITYALL_h8                              35 
#define  DENSITYALL_h9                              36 
#define  DENSITYALL_h10                             37 
#define  DENSITYALL_h11                             38 
#define  DENSITYALL_h12                             39 
#define  DENSITYALL_h13                             40 
#define  DENSITYALL_h14                             41 
#define  DENSITYALL_h15                             42 
#define  DENSITYALL_h16                             43 
#define  DENSITYALL_h17                             44 
#define  DENSITYALL_h18                             45 
#define  DENSITYALL_h19                             46 
#define  DENSITYALL_h20                             47 
#define  DENSITYALL_h21                             48 
#define  DENSITYALL_h22                             49 
#define  DENSITYALL_h23                             50 
#define  DENSITYALL_h24                             51 
#define  DENSITYALL_h25                             52 
#define  DENSITYALL_h26                             53 
#define  DENSITYALL_Init_UX_External                54 
#define  DENSITYALL_Init_UY_External                55 
#define  DENSITYALL_Init_UZ_External                56 
#define  DENSITYALL_Init_PhaseField_External        57 
#define  DENSITYALL_pnorm                           58 
#define  DENSITYALL_U                               59 
#define  DENSITYALL_V                               60 
#define  DENSITYALL_W                               61 
#define  DENSITYALL_nw_x                            62 
#define  DENSITYALL_nw_y                            63 
#define  DENSITYALL_nw_z                            64 
#define  DENSITYALL_IsSpecialBoundaryPoint          65 
#define DENSITY                                     66 
#define  DENSITY_g0                                  0 
#define  DENSITY_g1                                  1 
#define  DENSITY_g2                                  2 
#define  DENSITY_g3                                  3 
#define  DENSITY_g4                                  4 
#define  DENSITY_g5                                  5 
#define  DENSITY_g6                                  6 
#define  DENSITY_g7                                  7 
#define  DENSITY_g8                                  8 
#define  DENSITY_g9                                  9 
#define  DENSITY_g10                                10 
#define  DENSITY_g11                                11 
#define  DENSITY_g12                                12 
#define  DENSITY_g13                                13 
#define  DENSITY_g14                                14 
#define  DENSITY_g15                                15 
#define  DENSITY_g16                                16 
#define  DENSITY_g17                                17 
#define  DENSITY_g18                                18 
#define  DENSITY_g19                                19 
#define  DENSITY_g20                                20 
#define  DENSITY_g21                                21 
#define  DENSITY_g22                                22 
#define  DENSITY_g23                                23 
#define  DENSITY_g24                                24 
#define  DENSITY_g25                                25 
#define  DENSITY_g26                                26 
#define  DENSITY_h0                                 27 
#define  DENSITY_h1                                 28 
#define  DENSITY_h2                                 29 
#define  DENSITY_h3                                 30 
#define  DENSITY_h4                                 31 
#define  DENSITY_h5                                 32 
#define  DENSITY_h6                                 33 
#define  DENSITY_h7                                 34 
#define  DENSITY_h8                                 35 
#define  DENSITY_h9                                 36 
#define  DENSITY_h10                                37 
#define  DENSITY_h11                                38 
#define  DENSITY_h12                                39 
#define  DENSITY_h13                                40 
#define  DENSITY_h14                                41 
#define  DENSITY_h15                                42 
#define  DENSITY_h16                                43 
#define  DENSITY_h17                                44 
#define  DENSITY_h18                                45 
#define  DENSITY_h19                                46 
#define  DENSITY_h20                                47 
#define  DENSITY_h21                                48 
#define  DENSITY_h22                                49 
#define  DENSITY_h23                                50 
#define  DENSITY_h24                                51 
#define  DENSITY_h25                                52 
#define  DENSITY_h26                                53 
#define  DENSITY_Init_UX_External                   54 
#define  DENSITY_Init_UY_External                   55 
#define  DENSITY_Init_UZ_External                   56 
#define  DENSITY_Init_PhaseField_External           57 
#define  DENSITY_pnorm                              58 
#define  DENSITY_U                                  59 
#define  DENSITY_V                                  60 
#define  DENSITY_W                                  61 
#define  DENSITY_nw_x                               62 
#define  DENSITY_nw_y                               63 
#define  DENSITY_nw_z                               64 
#define  DENSITY_IsSpecialBoundaryPoint             65 
#define DENSITYAD                                    0 
#define GLOBALS                                     33 
#define  GLOBALS_Vfront                              0 
#define  GLOBALS_Vback                               1 
#define  GLOBALS_XLocation                           2 
#define  GLOBALS_PressureLoss                        3 
#define  GLOBALS_OutletFlux                          4 
#define  GLOBALS_InletFlux                           5 
#define  GLOBALS_TotalDensity                        6 
#define  GLOBALS_KineticEnergy                       7 
#define  GLOBALS_GasTotalVelocity                    8 
#define  GLOBALS_GasTotalVelocityX                   9 
#define  GLOBALS_GasTotalVelocityY                  10 
#define  GLOBALS_GasTotalVelocityZ                  11 
#define  GLOBALS_GasTotalPhase                      12 
#define  GLOBALS_LiqTotalVelocity                   13 
#define  GLOBALS_LiqTotalVelocityX                  14 
#define  GLOBALS_LiqTotalVelocityY                  15 
#define  GLOBALS_LiqTotalVelocityZ                  16 
#define  GLOBALS_NumFluidCells                      17 
#define  GLOBALS_NumSpecialPoints                   18 
#define  GLOBALS_NumWallBoundaryPoints              19 
#define  GLOBALS_NumBoundaryPoints                  20 
#define  GLOBALS_LiqTotalPhase                      21 
#define  GLOBALS_FluxNodeCount                      22 
#define  GLOBALS_FluxX                              23 
#define  GLOBALS_FluxY                              24 
#define  GLOBALS_FluxZ                              25 
#define  GLOBALS_Objective                          26 
#define  GLOBALS_InterfacePosition                  27 
#define  GLOBALS_InterfaceYTop                      28 
#define  GLOBALS_RTISpike                           29 
#define  GLOBALS_RTIBubble                          30 
#define  GLOBALS_RTISaddle                          31 
#define  GLOBALS_DropFront                          32 
#define QUANTITIES                                  85 
#define  QUANTITIES_SpecialBoundaryPoint             0 
#define  QUANTITIES_Rho                              1 
#define  QUANTITIES_PhaseField                       2 
#define  QUANTITIES_U                                3 
#define  QUANTITIES_P                                4 
#define  QUANTITIES_Pstar                            5 
#define  QUANTITIES_Normal                           6 
#define  QUANTITIES_IsItBoundary                     7 
#define  QUANTITIES_GradPhi                          8 
#define  QUANTITIES_WallPfF                          9 
#define  QUANTITIES_WallGradTangent                 10 
#define  QUANTITIES_WallTanCoeff                    11 
#define  QUANTITIES_WallPhasePred                   12 
#define  QUANTITIES_WallPhaseProfilePred            13 
#define  QUANTITIES_WallProfileDelta                14 
#define  QUANTITIES_WallPhaseSignedProfilePred      15 
#define  QUANTITIES_WallSignedProfileDelta          16 
#define  QUANTITIES_WallSignedLogitShift            17 
#define  QUANTITIES_WallFluidSampleCount            18 
#define  QUANTITIES_WallFluidSampleH                19 
#define  QUANTITIES_WallPhaseUnifiedProfilePred     20 
#define  QUANTITIES_WallUnifiedProfileDelta         21 
#define  QUANTITIES_WallBCPath                      22 
#define  QUANTITIES_WallH                           23 
#define  QUANTITIES_WallGeomNormal                  24 
#define  QUANTITIES_WallGrad1                       25 
#define  QUANTITIES_WallGrad2                       26 
#define  QUANTITIES_WallGradTangentVec              27 
#define  QUANTITIES_WallNormalCoeff1                28 
#define  QUANTITIES_WallNormalCoeff2                29 
#define  QUANTITIES_WallActualMinusProfile          30 
#define  QUANTITIES_WallActualMinusRaw              31 
#define  QUANTITIES_WallPhaseRawPred                32 
#define  QUANTITIES_WallPhaseSignedPred             33 
#define  QUANTITIES_WallContactResidual             34 
#define  QUANTITIES_WallSignedNormalGrad            35 
#define  QUANTITIES_WallTangentGradMag              36 
#define  QUANTITIES_WallSignedDeltaQ                37 
#define  QUANTITIES_WallSignedQClipped              38 
#define  QUANTITIES_BoundaryMask                    39 
#define  QUANTITIES_WallStage7Mode                  40 
#define  QUANTITIES_WallStage7ActiveWeight          41 
#define  QUANTITIES_WallStage7DeltaQRaw             42 
#define  QUANTITIES_WallStage7DeltaQLimited         43 
#define  QUANTITIES_WallStage7Denom                 44 
#define  QUANTITIES_WallStage7LimiterReason         45 
#define  QUANTITIES_WallStage7GradMag               46 
#define  QUANTITIES_WallStage7ActualCos             47 
#define  QUANTITIES_WallStage7TargetCos             48 
#define  QUANTITIES_WallStage7WriteCandidate        49 
#define  QUANTITIES_WallStage7WriteMinusProfile     50 
#define  QUANTITIES_WallStage8GradMode              51 
#define  QUANTITIES_WallStage8ActiveWeight          52 
#define  QUANTITIES_WallStage8NormalGradRaw         53 
#define  QUANTITIES_WallStage8NormalGradTarget      54 
#define  QUANTITIES_WallStage8ContactResidual       55 
#define  QUANTITIES_WallStage8TangentGradMag        56 
#define  QUANTITIES_WallStage8TargetCos             57 
#define  QUANTITIES_WallStage8GradWriteDeltaMag     58 
#define  QUANTITIES_WallStage8LimiterReason         59 
#define  QUANTITIES_WallStage8LocalWallAngle        60 
#define  QUANTITIES_WallStage8LocalWallNormal       61 
#define  QUANTITIES_WallStage8FluidWallAngle        62 
#define  QUANTITIES_WallStage8FluidWallNormal       63 
#define  QUANTITIES_WallStage8FluidWallDataCount     64 
#define  QUANTITIES_WallStage8GradCandidate         65 
#define  QUANTITIES_WallStage8GradCandidateUse      66 
#define  QUANTITIES_WallStage8NormalAgreement       67 
#define  QUANTITIES_WallStage8UsedGeomNormal        68 
#define  QUANTITIES_WallStage8TanCoeffLocal         69 
#define  QUANTITIES_WallStage8ThetaLocal            70 
#define  QUANTITIES_WallStage8PhaseC                71 
#define  QUANTITIES_WallStage8GradMagRaw            72 
#define  QUANTITIES_WallStage8TangentGradRaw        73 
#define  QUANTITIES_WallStage8TargetNormalGrad      74 
#define  QUANTITIES_WallStage8NormalDeltaRaw        75 
#define  QUANTITIES_WallStage8NormalDeltaLimited     76 
#define  QUANTITIES_WallStage8VectorDeltaRawMag     77 
#define  QUANTITIES_WallStage8VectorDeltaLimitedMag     78 
#define  QUANTITIES_WallStage8NormalLimiterHit      79 
#define  QUANTITIES_WallStage8VectorLimiterHit      80 
#define  QUANTITIES_WallStage8LimiterRatio          81 
#define  QUANTITIES_WallStage8RegionTag             82 
#define  QUANTITIES_WallStage8SphereRadialDot       83 
#define  QUANTITIES_WallStage8ContactBandTag        84 
#define SCALES                                       3 
#define  SCALES_dx                                   0 
#define  SCALES_dt                                   1 
#define  SCALES_dm                                   2 
#define FIELDS                                     112 
#define  FIELDS_g0                                   0 
#define  FIELDS_g1                                   1 
#define  FIELDS_g2                                   2 
#define  FIELDS_g3                                   3 
#define  FIELDS_g4                                   4 
#define  FIELDS_g5                                   5 
#define  FIELDS_g6                                   6 
#define  FIELDS_g7                                   7 
#define  FIELDS_g8                                   8 
#define  FIELDS_g9                                   9 
#define  FIELDS_g10                                 10 
#define  FIELDS_g11                                 11 
#define  FIELDS_g12                                 12 
#define  FIELDS_g13                                 13 
#define  FIELDS_g14                                 14 
#define  FIELDS_g15                                 15 
#define  FIELDS_g16                                 16 
#define  FIELDS_g17                                 17 
#define  FIELDS_g18                                 18 
#define  FIELDS_g19                                 19 
#define  FIELDS_g20                                 20 
#define  FIELDS_g21                                 21 
#define  FIELDS_g22                                 22 
#define  FIELDS_g23                                 23 
#define  FIELDS_g24                                 24 
#define  FIELDS_g25                                 25 
#define  FIELDS_g26                                 26 
#define  FIELDS_h0                                  27 
#define  FIELDS_h1                                  28 
#define  FIELDS_h2                                  29 
#define  FIELDS_h3                                  30 
#define  FIELDS_h4                                  31 
#define  FIELDS_h5                                  32 
#define  FIELDS_h6                                  33 
#define  FIELDS_h7                                  34 
#define  FIELDS_h8                                  35 
#define  FIELDS_h9                                  36 
#define  FIELDS_h10                                 37 
#define  FIELDS_h11                                 38 
#define  FIELDS_h12                                 39 
#define  FIELDS_h13                                 40 
#define  FIELDS_h14                                 41 
#define  FIELDS_h15                                 42 
#define  FIELDS_h16                                 43 
#define  FIELDS_h17                                 44 
#define  FIELDS_h18                                 45 
#define  FIELDS_h19                                 46 
#define  FIELDS_h20                                 47 
#define  FIELDS_h21                                 48 
#define  FIELDS_h22                                 49 
#define  FIELDS_h23                                 50 
#define  FIELDS_h24                                 51 
#define  FIELDS_h25                                 52 
#define  FIELDS_h26                                 53 
#define  FIELDS_Init_UX_External                    54 
#define  FIELDS_Init_UY_External                    55 
#define  FIELDS_Init_UZ_External                    56 
#define  FIELDS_Init_PhaseField_External            57 
#define  FIELDS_pnorm                               58 
#define  FIELDS_U                                   59 
#define  FIELDS_V                                   60 
#define  FIELDS_W                                   61 
#define  FIELDS_nw_x                                62 
#define  FIELDS_nw_y                                63 
#define  FIELDS_nw_z                                64 
#define  FIELDS_IsSpecialBoundaryPoint              65 
#define  FIELDS_IsBoundary                          66 
#define  FIELDS_gradPhiVal_x                        67 
#define  FIELDS_gradPhiVal_y                        68 
#define  FIELDS_gradPhiVal_z                        69 
#define  FIELDS_Stage8GradMode                      70 
#define  FIELDS_Stage8ActiveWeight                  71 
#define  FIELDS_Stage8NormalGradRaw                 72 
#define  FIELDS_Stage8NormalGradTarget              73 
#define  FIELDS_Stage8ContactResidual               74 
#define  FIELDS_Stage8TangentGradMag                75 
#define  FIELDS_Stage8TargetCos                     76 
#define  FIELDS_Stage8GradWriteDeltaMag             77 
#define  FIELDS_Stage8LimiterReason                 78 
#define  FIELDS_Stage8LocalWallAngle                79 
#define  FIELDS_Stage8LocalWallNormal_x             80 
#define  FIELDS_Stage8LocalWallNormal_y             81 
#define  FIELDS_Stage8LocalWallNormal_z             82 
#define  FIELDS_Stage8FluidWallAngle                83 
#define  FIELDS_Stage8FluidWallNormal_x             84 
#define  FIELDS_Stage8FluidWallNormal_y             85 
#define  FIELDS_Stage8FluidWallNormal_z             86 
#define  FIELDS_Stage8FluidWallDataCount            87 
#define  FIELDS_Stage8GradCandidate_x               88 
#define  FIELDS_Stage8GradCandidate_y               89 
#define  FIELDS_Stage8GradCandidate_z               90 
#define  FIELDS_Stage8GradCandidateUse              91 
#define  FIELDS_Stage8NormalAgreement               92 
#define  FIELDS_Stage8UsedGeomNormal                93 
#define  FIELDS_Stage8TanCoeffLocal                 94 
#define  FIELDS_Stage8ThetaLocal                    95 
#define  FIELDS_Stage8PhaseC                        96 
#define  FIELDS_Stage8GradMagRaw                    97 
#define  FIELDS_Stage8TangentGradRaw                98 
#define  FIELDS_Stage8TargetNormalGrad              99 
#define  FIELDS_Stage8NormalDeltaRaw               100 
#define  FIELDS_Stage8NormalDeltaLimited           101 
#define  FIELDS_Stage8VectorDeltaRawMag            102 
#define  FIELDS_Stage8VectorDeltaLimitedMag        103 
#define  FIELDS_Stage8NormalLimiterHit             104 
#define  FIELDS_Stage8VectorLimiterHit             105 
#define  FIELDS_Stage8LimiterRatio                 106 
#define  FIELDS_Stage8RegionTag                    107 
#define  FIELDS_Stage8SphereRadialDot              108 
#define  FIELDS_Stage8ContactBandTag               109 
#define  FIELDS_gradPhi_PhaseF                     110 
#define  FIELDS_PhaseF                             111 
#define STAGES                                      10 
#define  STAGES_PhaseInit                            0 
#define  STAGES_BaseInit                             1 
#define  STAGES_calcPhase                            2 
#define  STAGES_BaseIter                             3 
#define  STAGES_InitFromFieldsStage                  4 
#define  STAGES_WallInit_CA                          5 
#define  STAGES_calcWall_CA                          6 
#define  STAGES_calcPhaseGrad                        7 
#define  STAGES_calcPhaseGrad_init                   8 
#define  STAGES_calcWallPhase_correction             9 
#define ZONESETTINGS                                33 
#define  ZONESETTINGS_PhaseField                     0 
#define  ZONESETTINGS_radAngle                       1 
#define  ZONESETTINGS_Uavg                           2 
#define  ZONESETTINGS_VelocityX                      3 
#define  ZONESETTINGS_VelocityY                      4 
#define  ZONESETTINGS_VelocityZ                      5 
#define  ZONESETTINGS_Pressure                       6 
#define  ZONESETTINGS_VfrontInObj                    7 
#define  ZONESETTINGS_VbackInObj                     8 
#define  ZONESETTINGS_XLocationInObj                 9 
#define  ZONESETTINGS_PressureLossInObj             10 
#define  ZONESETTINGS_OutletFluxInObj               11 
#define  ZONESETTINGS_InletFluxInObj                12 
#define  ZONESETTINGS_TotalDensityInObj             13 
#define  ZONESETTINGS_KineticEnergyInObj            14 
#define  ZONESETTINGS_GasTotalVelocityInObj         15 
#define  ZONESETTINGS_GasTotalVelocityXInObj        16 
#define  ZONESETTINGS_GasTotalVelocityYInObj        17 
#define  ZONESETTINGS_GasTotalVelocityZInObj        18 
#define  ZONESETTINGS_GasTotalPhaseInObj            19 
#define  ZONESETTINGS_LiqTotalVelocityInObj         20 
#define  ZONESETTINGS_LiqTotalVelocityXInObj        21 
#define  ZONESETTINGS_LiqTotalVelocityYInObj        22 
#define  ZONESETTINGS_LiqTotalVelocityZInObj        23 
#define  ZONESETTINGS_NumFluidCellsInObj            24 
#define  ZONESETTINGS_NumSpecialPointsInObj         25 
#define  ZONESETTINGS_NumWallBoundaryPointsInObj     26 
#define  ZONESETTINGS_NumBoundaryPointsInObj        27 
#define  ZONESETTINGS_LiqTotalPhaseInObj            28 
#define  ZONESETTINGS_FluxNodeCountInObj            29 
#define  ZONESETTINGS_FluxXInObj                    30 
#define  ZONESETTINGS_FluxYInObj                    31 
#define  ZONESETTINGS_FluxZInObj                    32 
#define ACTIONS                                      3 
#define  ACTIONS_Iteration                           0 
#define  ACTIONS_Init                                1 
#define  ACTIONS_InitFields                          2 
#define IN_OBJ_OFFSET                                7 
#define SUM_GLOBALS                                 27 
#define ZONE_SHIFT                                  10 
#define ZONE_MAX                                    63 
#define DT_OFFSET                                 2079 
#define GRAD_OFFSET                               4158 
#define TIME_SEG                                  8316 

typedef unsigned short int flag_t;
typedef unsigned int big_flag_t;


enum eOperationType { Primal,Tangent,Adjoint,Optimize,SteadyAdjoint }; 
enum eCalculateGlobals { NoGlobals,IntegrateGlobals,OnlyObjective,IntegrateLast }; 
enum eModel { model_d3q27_pf_velocity_q27_geometric }; 
enum eAction { Iteration,Init,InitFields }; 
enum eStage { PhaseInit,BaseInit,calcPhase,BaseIter,InitFromFieldsStage,WallInit_CA,calcWall_CA,calcPhaseGrad,calcPhaseGrad_init,calcWallPhase_correction,Get }; 
enum eTape { NoTape,RecordTape }; 


#define OPTIONS_q27 1

#undef OPTIONS_OutFlow

#undef OPTIONS_BGK

#undef OPTIONS_thermo

#undef OPTIONS_planarBenchmark

#undef OPTIONS_autosym

#define OPTIONS_geometric 1

#undef OPTIONS_staircaseimp

#undef OPTIONS_isograd

#undef OPTIONS_tprec


#endif
