#!/usr/bin/env python3
"""Digest Stage14-B23/B24 probe roots into compact comparison tables.

The input root should contain one subdirectory per probe. Each probe directory
is expected to contain b23_key_summary.json or b24_key_summary.json generated by
stage14_b17_onset_mask_argmax.py. This script only summarizes diagnostic
evidence; it does not validate contact angle or promote a physics mode.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


ONSET_KEYS = [
    "first_b22_momentum_speed_onset",
    "first_b22_m0_speed_onset",
    "first_b22_phase_adv_speed_onset",
    "first_b21_heq_mach_onset",
    "first_phase_from_h_onset",
    "first_b22_force_over_rho_onset",
    "first_b22_force_pressure_onset",
    "first_b22_force_mu_onset",
    "first_force_over_rho_onset",
    "first_fmu_raw_onset",
    "first_pressure_input_onset",
    "first_stress_post_onset",
    "first_b18_force_raw_onset",
    "first_b18_force_floor_onset",
    "first_b18_force_phase_mix_onset",
]


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def onset_step(summary: dict[str, Any], key: str) -> Any:
    onset = summary.get(key)
    if isinstance(onset, dict):
        return onset.get("step")
    return None


def onset_value(summary: dict[str, Any], key: str) -> Any:
    onset = summary.get(key)
    if isinstance(onset, dict):
        return onset.get("value")
    return None


def read_case_metadata(probe_dir: Path) -> dict[str, Any]:
    matches = list(probe_dir.glob("*/case_metadata.json"))
    if not matches:
        return {}
    return load_json(matches[0])


def summary_paths(root: Path) -> list[Path]:
    paths = sorted(root.glob("*/b23_key_summary.json"))
    paths.extend(sorted(root.glob("*/b24_key_summary.json")))
    return paths


def build_rows(root: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for path in summary_paths(root):
        probe_dir = path.parent
        summary = load_json(path)
        metadata = read_case_metadata(probe_dir)
        row: dict[str, Any] = {
            "probe": probe_dir.name,
            "summary": str(path),
            "prefix": path.name.split("_", 1)[0],
            "binary_sha256": metadata.get("binary_sha256"),
            "iterations": metadata.get("iterations"),
            "density_l": metadata.get("density_l"),
            "phase_advection_velocity_mode": metadata.get("phase_advection_velocity_mode"),
            "momentum_closure_probe_mode": metadata.get("momentum_closure_probe_mode"),
            "momentum_force_mode": metadata.get("momentum_force_mode"),
            "pressure_closure_mode": metadata.get("pressure_closure_mode"),
            "force_density_closure_mode": metadata.get("force_density_closure_mode"),
            "force_fixed_point_mode": metadata.get("force_fixed_point_mode"),
            "b22_velocity_producer_audit_mode": metadata.get("b22_velocity_producer_audit_mode"),
            "primary_branch": summary.get("primary_branch"),
            "b18_primary_branch": summary.get("b18_primary_branch"),
            "b20_primary_branch": summary.get("b20_primary_branch"),
            "b21_primary_branch": summary.get("b21_primary_branch"),
            "b22_primary_branch": summary.get("b22_primary_branch"),
            "b22_primary_branch_reason": summary.get("b22_primary_branch_reason"),
        }
        for key in ONSET_KEYS:
            row[f"{key}_step"] = onset_step(summary, key)
            row[f"{key}_value"] = onset_value(summary, key)
        rows.append(row)
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = sorted({key for row in rows for key in row})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("--csv", type=Path)
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()

    rows = build_rows(args.root)
    if args.csv:
        write_csv(args.csv, rows)
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(json.dumps(rows, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(rows, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
