#!/usr/bin/env python3
"""Rank Stage14-B41 stress-source candidates from B40-instrumented stats.

B41 is intentionally analysis-only. It reuses the B40 stress-construction
diagnostic fields because they already expose the relevant stress definitions.
This script consumes the generic ``*_mask_stats.csv`` generated by
``stage14_b17_onset_mask_argmax.py`` and produces a compact candidate ranking
for B42 active-closure implementation.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any


MASK_PRIORITY = [
    "low_rho",
    "interface_wide",
    "near_wall",
    "near_interface_wall",
    "fluid_all",
    "all_cells",
]


@dataclass(frozen=True)
class Candidate:
    name: str
    stress_field: str
    fmu_field: str | None
    force_field: str | None
    active_mode_hint: str
    notes: str


CANDIDATES = [
    Candidate(
        name="legacy_relaxed_moment",
        stress_field="B40StressMomentRelaxedNorm",
        fmu_field="B40FmuMomentRelaxedLegacyNorm",
        force_field="B40ForceOverRhoMomentRelaxedLegacyNorm",
        active_mode_hint="existing legacy path / baseline",
        notes="Current relaxed moment stress used by active F_mu.",
    ),
    Candidate(
        name="raw_moment_preforce",
        stress_field="B40StressMomentRawNorm",
        fmu_field="B40FmuMomentRawLegacyNorm",
        force_field="B40ForceOverRhoMomentRawLegacyNorm",
        active_mode_hint="B42 candidate mode 3",
        notes="Pre-force raw moment residual without Omega relaxation.",
    ),
    Candidate(
        name="incoming_raw_population",
        stress_field="B40StressIncomingRawNorm",
        fmu_field="B40FmuIncomingRawLegacyNorm",
        force_field=None,
        active_mode_hint="shadow only unless B42 adds force reconstruction",
        notes="Raw incoming second moment; not directly a non-equilibrium stress.",
    ),
    Candidate(
        name="incoming_neq_preforce",
        stress_field="B40StressIncomingNeqPreNorm",
        fmu_field="B40FmuIncomingNeqPreLegacyNorm",
        force_field=None,
        active_mode_hint="existing FmuStressClosureMode=2 / compare only",
        notes="Incoming population minus pre-force equilibrium.",
    ),
    Candidate(
        name="bgk_pop_neq_preforce",
        stress_field="B40StressBGKPopNeqPreNorm",
        fmu_field="B40FmuBGKPopNeqPreBGKNorm",
        force_field="B40ForceOverRhoBGKPopNeqPreBGKNorm",
        active_mode_hint="B42 candidate mode 4",
        notes="Pre-force population non-equilibrium with BGK-like scale.",
    ),
    Candidate(
        name="post_force_shadow",
        stress_field="B40StressPostForceNorm",
        fmu_field="B40FmuPostForceLegacyNorm",
        force_field=None,
        active_mode_hint="reject as active source",
        notes="Post-force stress shadow; diagnostic feedback amplifier.",
    ),
]


def parse_float(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    try:
        out = float(value)
    except ValueError:
        return None
    if not math.isfinite(out):
        return None
    return out


def load_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = [dict(row) for row in reader]
    for row in rows:
        row["step"] = int(row["step"])
        row["present"] = str(row.get("present", "")).lower() == "true"
        for key in ["max_abs", "max", "min", "mean", "p99_abs", "p999_abs", "nonfinite_count"]:
            row[key] = parse_float(row.get(key))
    return rows


def by_field_mask(rows: list[dict[str, Any]]) -> dict[tuple[str, str, int], dict[str, Any]]:
    out: dict[tuple[str, str, int], dict[str, Any]] = {}
    for row in rows:
        if row.get("present"):
            out[(str(row["field"]), str(row["mask"]), int(row["step"]))] = row
    return out


def value(index: dict[tuple[str, str, int], dict[str, Any]], field: str, mask: str, step: int) -> float | None:
    row = index.get((field, mask, step))
    if not row:
        return None
    return row.get("max_abs")


def first_crossing(
    index: dict[tuple[str, str, int], dict[str, Any]],
    field: str | None,
    mask: str,
    threshold: float,
    steps: list[int],
) -> dict[str, Any] | None:
    if field is None:
        return None
    for step in steps:
        v = value(index, field, mask, step)
        if v is not None and v > threshold:
            return {"step": step, "value": v, "threshold": threshold}
    return None


def score_candidate(
    candidate: Candidate,
    index: dict[tuple[str, str, int], dict[str, Any]],
    mask: str,
    baseline_force: float | None,
    steps: list[int],
    focus_step: int,
) -> dict[str, Any]:
    stress_focus = value(index, candidate.stress_field, mask, focus_step)
    fmu_focus = value(index, candidate.fmu_field, mask, focus_step) if candidate.fmu_field else None
    force_focus = value(index, candidate.force_field, mask, focus_step) if candidate.force_field else None
    if force_focus is None and fmu_focus is not None:
        # Conservative proxy. Actual force-over-rho also includes pressure/surface/body
        # and rho_eff, so do not use this proxy for pass/fail.
        force_proxy = None
    else:
        force_proxy = force_focus
    stress_first = first_crossing(index, candidate.stress_field, mask, 1.0e3, steps)
    fmu_first = first_crossing(index, candidate.fmu_field, mask, 1.0e3, steps) if candidate.fmu_field else None
    force_first = first_crossing(index, candidate.force_field, mask, 1.0e3, steps) if candidate.force_field else None
    force_ratio = None
    if force_focus is not None and baseline_force and baseline_force > 0.0:
        force_ratio = force_focus / baseline_force
    rank_score = 1.0e300
    if force_focus is not None:
        rank_score = force_focus
    elif fmu_focus is not None:
        rank_score = fmu_focus
    elif stress_focus is not None:
        rank_score = stress_focus
    return {
        "candidate": candidate.name,
        "mask": mask,
        "focus_step": focus_step,
        "stress_field": candidate.stress_field,
        "fmu_field": candidate.fmu_field,
        "force_field": candidate.force_field,
        "stress_at_focus": stress_focus,
        "fmu_at_focus": fmu_focus,
        "force_over_rho_at_focus": force_focus,
        "force_proxy_at_focus": force_proxy,
        "force_vs_legacy_ratio": force_ratio,
        "first_stress_gt_1e3": stress_first,
        "first_fmu_gt_1e3": fmu_first,
        "first_force_over_rho_gt_1e3": force_first,
        "rank_score": rank_score,
        "active_mode_hint": candidate.active_mode_hint,
        "notes": candidate.notes,
    }


def select_focus_step(rows: list[dict[str, Any]], preferred: int | None) -> int:
    steps = sorted({int(row["step"]) for row in rows})
    if preferred is not None and preferred in steps:
        return preferred
    # Prefer the known B40 first force-over-rho onset if present.
    for row in rows:
        if (
            row.get("field") == "ForceOverRhoNorm"
            and row.get("mask") == "low_rho"
            and row.get("max_abs") is not None
            and row["max_abs"] > 1.0e3
        ):
            return int(row["step"])
    return steps[-1]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = [
        "candidate",
        "mask",
        "focus_step",
        "stress_at_focus",
        "fmu_at_focus",
        "force_over_rho_at_focus",
        "force_vs_legacy_ratio",
        "rank_score",
        "active_mode_hint",
        "notes",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key) for key in fieldnames})


def fmt(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def write_md(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# Stage14-B41 Stress-Source Audit",
        "",
        "Status: diagnostic ranking only. This is not a solver repair, not contact-angle validation, and not dynamic-impact readiness.",
        "",
        "B41 reuses the B40 stress-construction fields by design. No TCLB solver field or active physics path is changed in B41.",
        "",
        f"Input stats: `{summary['input_mask_stats']}`",
        f"Focus step: `{summary['focus_step']}`",
        f"Primary mask: `{summary['primary_mask']}`",
        f"Verdict: `{summary['verdict']}`",
        "",
        "## Primary Ranking",
        "",
        "| rank | candidate | stress | F_mu | F/rho | F/rho / legacy | B42 hint |",
        "| ---: | --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for rank, row in enumerate(summary["primary_ranking"], start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(rank),
                    row["candidate"],
                    fmt(row["stress_at_focus"]),
                    fmt(row["fmu_at_focus"]),
                    fmt(row["force_over_rho_at_focus"]),
                    fmt(row["force_vs_legacy_ratio"]),
                    row["active_mode_hint"],
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## B42 Recommendation",
            "",
            summary["recommendation"],
            "",
            "## Guardrails",
            "",
            "- Keep B42 modes default-off.",
            "- Do not use post-force shadow stress as an active source.",
            "- Do not claim contact-angle validation from B41/B42.",
            "- If no candidate improves the force/stress metrics, escalate to F_mu coefficient derivation before more runtime tuning.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def build_summary(mask_stats: Path, focus_step: int | None) -> dict[str, Any]:
    rows = load_rows(mask_stats)
    if not rows:
        raise SystemExit(f"No rows in {mask_stats}")
    index = by_field_mask(rows)
    steps = sorted({int(row["step"]) for row in rows})
    focus = select_focus_step(rows, focus_step)
    rankings_by_mask: dict[str, list[dict[str, Any]]] = {}
    for mask in MASK_PRIORITY:
        baseline = value(index, "B40ForceOverRhoMomentRelaxedLegacyNorm", mask, focus)
        ranked = [
            score_candidate(candidate, index, mask, baseline, steps, focus)
            for candidate in CANDIDATES
        ]
        ranked.sort(key=lambda row: (row["rank_score"] is None, float(row["rank_score"] or 1.0e300)))
        rankings_by_mask[mask] = ranked
    primary_mask = "low_rho" if rankings_by_mask.get("low_rho") else MASK_PRIORITY[0]
    primary = rankings_by_mask[primary_mask]
    implementation_candidates = [
        row
        for row in primary
        if row["candidate"] in {"raw_moment_preforce", "bgk_pop_neq_preforce", "incoming_neq_preforce"}
    ]
    implementation_candidates.sort(key=lambda row: float(row["rank_score"] or 1.0e300))
    legacy = next((row for row in primary if row["candidate"] == "legacy_relaxed_moment"), None)
    legacy_force = legacy.get("force_over_rho_at_focus") if legacy else None
    better_than_legacy = [
        row
        for row in implementation_candidates
        if (
            row.get("force_over_rho_at_focus") is not None
            and legacy_force is not None
            and row["force_over_rho_at_focus"] < legacy_force
        )
    ]
    if better_than_legacy:
        top = better_than_legacy[0]
        recommendation = (
            f"Start B42 with `{top['candidate']}` ({top['active_mode_hint']}) and keep a second "
            "mode for the next-best independent stress definition. Compare against legacy with identical "
            "pressure/rho/h settings."
        )
        verdict = "b41_candidate_ranked"
    elif implementation_candidates:
        recommendation = (
            "Do not directly promote the rankable raw/BGK pre-force candidates into active B42 modes: "
            "their force-over-rho at the focus step is not better than the legacy relaxed-moment path. "
            "Use B42 for a new physically motivated stress definition, such as deviatoric/pressure-removed "
            "incoming stress or moment-wise MRT scaling, and use B43 derivation before any default-off "
            "candidate is treated as a repair."
        )
        verdict = "b41_no_better_implementable_candidate"
    else:
        recommendation = "No implementable stress source candidate was rankable; inspect field presence before B42."
        verdict = "b41_candidate_missing"
    return {
        "claim_limit": "B41 diagnostic ranking only; not a solver repair",
        "input_mask_stats": str(mask_stats),
        "focus_step": focus,
        "steps": steps,
        "primary_mask": primary_mask,
        "verdict": verdict,
        "primary_ranking": primary,
        "rankings_by_mask": rankings_by_mask,
        "recommendation": recommendation,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mask_stats", type=Path)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--focus-step", type=int, default=None)
    parser.add_argument("--prefix", default="b41")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    summary = build_summary(args.mask_stats, args.focus_step)

    out_json = args.out_dir / f"{args.prefix}_stress_source_ranking.json"
    out_csv = args.out_dir / f"{args.prefix}_stress_source_ranking.csv"
    out_md = args.out_dir / f"{args.prefix}_stress_source_ranking.md"
    out_json.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    write_csv(out_csv, summary["primary_ranking"])
    write_md(out_md, summary)
    print(json.dumps({"verdict": summary["verdict"], "out_json": str(out_json)}, indent=2))
    return 0 if summary["verdict"] in {"b41_candidate_ranked", "b41_no_better_implementable_candidate"} else 2


if __name__ == "__main__":
    raise SystemExit(main())
